name: CI

on:
  push:
    branches: [ test-CI ]
  pull_request:
    branches: [ test-CI ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you want to use    

    - name: Install Package in Editable Mode with Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2' # Use the R version you prefer

    - name: Install R packages
      # uses: r-lib/actions/setup-r-dependencies@v2
      # with:
      #   cache: true
      #   cache-version: 1
      #   dependencies: '"Suggests"'
      #   packages: |
      #     devtools
      #     grf
      #     causalweight
      #     mediation
      run: |
        mkdir -p $HOME/R
        export R_LIBS_USER=$HOME/R
        R -q -e 'install.packages("pak", repos = "https://r-lib.github.io/p/pak/stable/", lib = Sys.getenv("R_LIBS_USER"))'
        R -q -e 'library(pak)'
        R -q -e 'pak::pkg_install(c("grf", "causalweight", "mediation", "ohines/plmed"))'

    # - name: Install plmed package          
    #   run: |    
    #     R -e "pak::pkg_install('ohines/plmed')"

    - name: Install Pytest
      run: |
        pip install pytest

    - name: Run tests
      run: |
        pytest
