name: CI

on:
  push:
    branches: [ test-CI ]
  pull_request:
    branches: [ test-CI ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you want to use

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn numpy scipy seaborn matplotlib rpy2

    - name: Install R and R packages
      run: |
        sudo apt-get update
        sudo apt-get install r-base r-base-dev

        # Create a directory for R packages in the GitHub workspace
        mkdir -p $HOME/R

        # Set R_LIBS_USER environment variable to the custom library directory
        export R_LIBS_USER=$HOME/R

        Rscript -e 'install.packages("grf", repos="https://cran.rstudio.com/", quiet=TRUE, lib=Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'install.packages("causalweight", repos="https://cran.rstudio.com/", quiet=TRUE, lib=Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'install.packages("mediation", repos="https://cran.rstudio.com/", quiet=TRUE, lib=Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'install.packages("devtools", repos="https://cran.rstudio.com/", quiet=TRUE, lib=Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'devtools::install_github("ohines/plmed", quiet=TRUE, lib=Sys.getenv("R_LIBS_USER"))'

    - name: Run tests
      run: |
        pytest
