name: CI

on:
  push:
    branches: [ test-CI ]
  pull_request:
    branches: [ test-CI ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you want to use

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn numpy scipy seaborn matplotlib rpy2

    - name: Install R and R packages
      run: |
        sudo apt-get update
        sudo apt-get install r-base r-base-dev
        Rscript -e 'install.packages(c("grf", "causalweight", "mediation"))'
        Rscript -e 'install.packages("devtools")'
        Rscript -e 'devtools::install_github("ohines/plmed")'

    - name: Run tests
      run: |
        pytest
