name: CI

on:
  push:
    branches: [ test-CI ]
  pull_request:
    branches: [ test-CI ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you want to use

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: $HOME/R
        key: ${{ runner.os }}-R
        restore-keys: |
          ${{ runner.os }}-R-       

    - name: Install Package in Editable Mode with Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2' # Use the R version you prefer

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        extra-packages: |
          grf
          causalweight
          mediation
          devtools

    - name: Install other R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        extra-packages: |
          ohines/plmed

    - name: Run tests
      run: |
        pytest
